### PR TITLE
🇫🇷 french version for this awesome tutorial

### PR DESCRIPTION
**Pull request by unchained-42**
I made a french version of your tuto because it's very easy to understand the basic of bitcoin for beginner but in France many people don't read English. 

What i did :

- Simply translate the english text to french
- Added a button in the header to change the language

### CODE REVIEW

**Comment by satsie** [comment]
Thank you!! This is amazing! I won't have time to look into internationalization until the week after next, so I'm going to leave this PR open until then. 

~~Ideally I'd like to have a selection area where the user can pick their language.~~ EDIT: I see you added a button! Let me checkout the changes, run them locally and do a spot check. 

I like how you've made this a separate page, but I also want to evaluate a few more I18N solutions. I'm just worried if I make future updates to the English version, I don't want to break any of the translated pages! :) 

Will revisit this soon. Thank you so much for this contribution!

**Comment by felipebrunet** [comment]
awesome site thanks!!! 
I will translate it to spanish right away (and test it on my site in the meantime), as soon as I finish it I'll send you the translated html and point the tutorial to your website.

**Comment by satsie** [comment]
Merci @kevin-btc! I've never made edits to a PR before, so I followed [this guide](https://ardupilot.org/dev/docs/editing-prs.html). I didn't realize it would make changes to your branch directly, so I apologize for that.

Regarding this PR, I believe you have a linter or an auto formatter that introduced a lot of styling changes. I'm open to that and hope to set up a linter in the code base at some point, but your diff made it very hard to see the actual code changes. I ended up reverting a lot of the changes made to the `gulpfile` and `main.less`. I also restored the `build` directory because I still have an s3 job that I believe is reading from this (though in theory, everything should be built on the fly and deployed from the `deploy` directory).

I ran this locally and it all looks wonderful to me! Going to merge now. Thank you for your hard work doing the translation and for the updates to link to the French version from the main index. I really appreciate it!

**Comment by satsie** [comment]
thank you @felipebrunet! Feel free to make a PR with a `.html` file, similar to what kevin-btc did with `fr.html`. I am happy to make sure it gets added to the available languages.

**Comment by felipebrunet** [comment]
Great, I'll do it that way. Will send the PR in a few hours.  Thanks!

**Comment by unchained-42** [comment]
Oh sorry if it was hard to see the code changes due to my linter ! i didn't pay attention to that. Thank you so much for adding the translation to your website ! it's awesome.

**Pull request merged**
