### PR TITLE
Text to include quotation marks in the command

### PR DESCRIPTION
**Pull request by ecurrencyhodler**
I didn't realize I needed to include quotation marks. Might be helpful to call that out. Here's my suggestion but feel free to revise the copy.

This is such a cool project and I wish I had something like this when I first was exploring Bitcoin. Great work Satsie and thank you so much!

### CODE REVIEW

**Comment by satsie** [comment]
Thanks for the PR! I think you've honed in on an issue with the instructions that a small, but significant percentage of people are hitting. You don't need to type anything in quotes, everything you need has been saved to a variable. 

`verifySignature(publicKey, message, signature)` should work exactly as typed. Is this by any chance where you were running into copy/paste problems too? If so, I could use some help on how to word this to make it more obvious :sweat_smile: 

Screenshot from 2022-10-10 10-18-13

**Comment by ecurrencyhodler** [comment]
Hmmm that's strange. I tried typing it without the quotation marks but hit an error. Maybe I missed something!

>If so, I could use some help on how to word this to make it more obvious

As a non-coder, I have no idea what a variable means. Maybe including a one liner on what a variable is? Or explicitly call out that they don't need to use quotation marks. Maybe something like this?

"Similar to the previous lesson, this tutorial has automatically converted the `publicKey`, `message`, and `signature` you generated into variables of the same name so that you don't need to include quotation marks when using them in a command."

Also wow, this is quickly becoming a CS class.

**Comment by satsie** [comment]
Just to be clear, you are doing something like:

```
verifySignature('DFF1D77F2A671C5F36183726DB2341BE58FEAE1DA2DECED843240F7B502BA659', 'my message', '18dd62c312a59e628f16c8134dc7df6566a233e179c4fb56b7c40a1fc56360a57c7ed6bbc9d326e508d65689d7c5f01685732201b0f788f4ee880a68637b45e1')
```

But I'm saying you only need to do:

```
verifySignature(publicKey, message, signature)
```

In fact, I didn't anticipate that there would be several people doing your approach (which is cool!)

I found the code causing the copy/paste problems. It's code that focuses/"activates" the input text box when you click anywhere in the console. It's not a great experience if I remove that bit, but I can see the frustration when it comes to trying to highlight text. I think fixing the instructions to prevent anyone from needing to highlight might be the best option. Prevent anyone from having to go down this path in the first place.

**Comment by CoderBoogs** [comment]
I ran into the same issue as well. I had to put ‘any message’ in quotes for it to work. For beginners who might not know what a variable is just having the word message there is very confusing.

**Pull request closed without merging**
